use crate::shared::i18n::AppLanguage;

#[derive(Clone, Copy)]
pub(super) struct ExercisesCopy {
    pub form_title: &'static str,
    pub edit_title: &'static str,
    pub list_title: &'static str,
    pub name_label: &'static str,
    pub group_label: &'static str,
    pub create_button: &'static str,
    pub update_button: &'static str,
    pub cancel_button: &'static str,
    pub refresh_button: &'static str,
    pub edit_button: &'static str,
    pub delete_button: &'static str,
    pub name_column: &'static str,
    pub group_column: &'static str,
    pub actions_column: &'static str,
    pub empty_state: &'static str,
    pub name_required: &'static str,
    pub created_message: &'static str,
    pub updated_message: &'static str,
    pub deleted_message: &'static str,
}

pub(super) fn copy(language: AppLanguage) -> ExercisesCopy {
    match language {
        AppLanguage::English => ExercisesCopy {
            form_title: "Create exercise",
            edit_title: "Edit exercise",
            list_title: "Exercises",
            name_label: "Exercise name",
            group_label: "Muscle group",
            create_button: "Create exercise",
            update_button: "Update exercise",
            cancel_button: "Cancel editing",
            refresh_button: "Refresh",
            edit_button: "Edit",
            delete_button: "Delete",
            name_column: "Name",
            group_column: "Group",
            actions_column: "Actions",
            empty_state: "No exercises yet.",
            name_required: "Exercise name is required",
            created_message: "Exercise created",
            updated_message: "Exercise updated",
            deleted_message: "Exercise deleted",
        },
        AppLanguage::Ukrainian => ExercisesCopy {
            form_title: "Створення вправи",
            edit_title: "Редагування вправи",
            list_title: "Вправи",
            name_label: "Назва вправи",
            group_label: "Група м'язів",
            create_button: "Створити вправу",
            update_button: "Оновити вправу",
            cancel_button: "Скасувати редагування",
            refresh_button: "Оновити",
            edit_button: "Редагувати",
            delete_button: "Видалити",
            name_column: "Назва",
            group_column: "Група",
            actions_column: "Дії",
            empty_state: "Вправ поки немає.",
            name_required: "Потрібно вказати назву вправи",
            created_message: "Вправу створено",
            updated_message: "Вправу оновлено",
            deleted_message: "Вправу видалено",
        },
    }
}
