use crate::shared::i18n::AppLanguage;

#[derive(Clone, Copy)]
pub(crate) struct WorkoutsCopy {
    pub form_title: &'static str,
    pub edit_form_title: &'static str,
    pub list_title: &'static str,
    pub title_label: &'static str,
    pub date_label: &'static str,
    pub create_button: &'static str,
    pub update_button: &'static str,
    pub cancel_button: &'static str,
    pub workout_created: &'static str,
    pub workout_updated: &'static str,
    pub workout_deleted: &'static str,
    pub title_required: &'static str,
    pub empty_workouts: &'static str,
    pub sets_title: &'static str,
    pub no_exercises: &'static str,
    pub add_set_button: &'static str,
    pub update_set_button: &'static str,
    pub cancel_set_button: &'static str,
    pub invalid_set: &'static str,
    pub set_updated: &'static str,
    pub set_deleted: &'static str,
    pub empty_sets: &'static str,
    pub edit_button: &'static str,
    pub delete_button: &'static str,
    pub weight_label: &'static str,
    pub reps_label: &'static str,
    pub exercise_column: &'static str,
    pub weight_column: &'static str,
    pub reps_column: &'static str,
    pub actions_column: &'static str,
}

pub(crate) fn copy(language: AppLanguage) -> WorkoutsCopy {
    match language {
        AppLanguage::English => WorkoutsCopy {
            form_title: "Create workout",
            edit_form_title: "Edit workout",
            list_title: "Workouts",
            title_label: "Workout title",
            date_label: "Workout date (YYYY-MM-DD)",
            create_button: "Create workout",
            update_button: "Update workout",
            cancel_button: "Cancel editing",
            workout_created: "Workout created",
            workout_updated: "Workout updated",
            workout_deleted: "Workout deleted",
            title_required: "Workout title is required",
            empty_workouts: "No workouts yet.",
            sets_title: "Workout sets",
            no_exercises: "Create an exercise before adding sets.",
            add_set_button: "Add set",
            update_set_button: "Update set",
            cancel_set_button: "Cancel set editing",
            invalid_set: "Weight and repetitions must be valid numbers",
            set_updated: "Set updated",
            set_deleted: "Set deleted",
            empty_sets: "No sets in this workout yet.",
            edit_button: "Edit",
            delete_button: "Delete",
            weight_label: "Weight",
            reps_label: "Repetitions",
            exercise_column: "Exercise",
            weight_column: "Weight",
            reps_column: "Repetitions",
            actions_column: "Actions",
        },
        AppLanguage::Ukrainian => WorkoutsCopy {
            form_title: "Створення тренування",
            edit_form_title: "Редагування тренування",
            list_title: "Тренування",
            title_label: "Назва тренування",
            date_label: "Дата тренування (YYYY-MM-DD)",
            create_button: "Створити тренування",
            update_button: "Оновити тренування",
            cancel_button: "Скасувати редагування",
            workout_created: "Тренування створено",
            workout_updated: "Тренування оновлено",
            workout_deleted: "Тренування видалено",
            title_required: "Потрібно вказати назву тренування",
            empty_workouts: "Тренувань поки немає.",
            sets_title: "Підходи тренування",
            no_exercises: "Спочатку створіть вправу.",
            add_set_button: "Додати підхід",
            update_set_button: "Оновити підхід",
            cancel_set_button: "Скасувати редагування підходу",
            invalid_set: "Вага та повторення мають бути коректними числами",
            set_updated: "Підхід оновлено",
            set_deleted: "Підхід видалено",
            empty_sets: "У цьому тренуванні ще немає підходів.",
            edit_button: "Редагувати",
            delete_button: "Видалити",
            weight_label: "Вага",
            reps_label: "Повторення",
            exercise_column: "Вправа",
            weight_column: "Вага",
            reps_column: "Повторення",
            actions_column: "Дії",
        },
    }
}
